/***********************************************************************************************************************
 * Copyright (C) 2010-2013 by the Stratosphere project (http://stratosphere.eu)
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 * ********************************************************************************************************************/
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoTuple.proto
// This file has been modified. Do not replace without checking sections marked with //MODIFICATION.
package eu.stratosphere.languagebinding.api.java.proto;

public final class ProtocolTuple {
	private ProtocolTuple() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface TupleSizeOrBuilder
			extends com.google.protobuf.MessageOrBuilder {

		// required sfixed32 value = 1;
		/**
		 * <code>required sfixed32 value = 1;</code>
		 */
		boolean hasValue();

		/**
		 * <code>required sfixed32 value = 1;</code>
		 */
		int getValue();
	}

	/**
	 * Protobuf type {@code eu.stratosphere.languagebinding.api.java.proto.TupleSize}
	 */
	public static final class TupleSize extends
			com.google.protobuf.GeneratedMessage
			implements TupleSizeOrBuilder {
		// Use TupleSize.newBuilder() to construct.
		private TupleSize(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
			super(builder);
			this.unknownFields = builder.getUnknownFields();
		}

		private TupleSize(boolean noInit) {
			this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
		}

		private static final TupleSize defaultInstance;

		public static TupleSize getDefaultInstance() {
			return defaultInstance;
		}

		public TupleSize getDefaultInstanceForType() {
			return defaultInstance;
		}

		private final com.google.protobuf.UnknownFieldSet unknownFields;

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet
				getUnknownFields() {
			return this.unknownFields;
		}

		private TupleSize(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			initFields();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields
					= com.google.protobuf.UnknownFieldSet.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
						case 0:
							done = true;
							break;
						default: {
							if (!parseUnknownField(input, unknownFields,
									extensionRegistry, tag)) {
								done = true;
							}
							break;
						}
						case 13: {
							bitField0_ |= 0x00000001;
							value_ = input.readSFixed32();
							break;
						}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
						e.getMessage()).setUnfinishedMessage(this);
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor
				getDescriptor() {
			return eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.internal_static_eu_stratosphere_languagebinding_api_java_proto_TupleSize_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
				internalGetFieldAccessorTable() {
			return eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.internal_static_eu_stratosphere_languagebinding_api_java_proto_TupleSize_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.TupleSize.class, eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.TupleSize.Builder.class);
		}

		public static com.google.protobuf.Parser<TupleSize> PARSER
				= new com.google.protobuf.AbstractParser<TupleSize>() {
					public TupleSize parsePartialFrom(
							com.google.protobuf.CodedInputStream input,
							com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
						return new TupleSize(input, extensionRegistry);
					}
				};

		@java.lang.Override
		public com.google.protobuf.Parser<TupleSize> getParserForType() {
			return PARSER;
		}

		private int bitField0_;
		// required sfixed32 value = 1;
		public static final int VALUE_FIELD_NUMBER = 1;
		private int value_;

		/**
		 * <code>required sfixed32 value = 1;</code>
		 */
		public boolean hasValue() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		/**
		 * <code>required sfixed32 value = 1;</code>
		 */
		public int getValue() {
			return value_;
		}

		private void initFields() {
			value_ = 0;
		}
		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1) {
				return isInitialized == 1;
			}

			if (!hasValue()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeSFixed32(1, value_);
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1) {
				return size;
			}

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream
						.computeSFixed32Size(1, value_);
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.TupleSize parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.TupleSize parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.TupleSize parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.TupleSize parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.TupleSize parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.TupleSize parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.TupleSize parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input);
		}

		public static eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.TupleSize parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input, extensionRegistry);
		}

		public static eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.TupleSize parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.TupleSize parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.TupleSize prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code eu.stratosphere.languagebinding.api.java.proto.TupleSize}
		 */
		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.TupleSizeOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor
					getDescriptor() {
				return eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.internal_static_eu_stratosphere_languagebinding_api_java_proto_TupleSize_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
					internalGetFieldAccessorTable() {
				return eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.internal_static_eu_stratosphere_languagebinding_api_java_proto_TupleSize_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.TupleSize.class, eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.TupleSize.Builder.class);
			}

			// Construct using eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.TupleSize.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
					com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				value_ = 0;
				bitField0_ = (bitField0_ & ~0x00000001);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor
					getDescriptorForType() {
				return eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.internal_static_eu_stratosphere_languagebinding_api_java_proto_TupleSize_descriptor;
			}

			public eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.TupleSize getDefaultInstanceForType() {
				return eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.TupleSize.getDefaultInstance();
			}

			public eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.TupleSize build() {
				eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.TupleSize result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.TupleSize buildPartial() {
				eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.TupleSize result = new eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.TupleSize(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.value_ = value_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.TupleSize) {
					return mergeFrom((eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.TupleSize) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.TupleSize other) {
				if (other == eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.TupleSize.getDefaultInstance()) {
					return this;
				}
				if (other.hasValue()) {
					setValue(other.getValue());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasValue()) {

					return false;
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.TupleSize parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.TupleSize) e.getUnfinishedMessage();
					throw e;
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}
			private int bitField0_;

			// required sfixed32 value = 1;
			private int value_;

			/**
			 * <code>required sfixed32 value = 1;</code>
			 */
			public boolean hasValue() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <code>required sfixed32 value = 1;</code>
			 */
			public int getValue() {
				return value_;
			}

			/**
			 * <code>required sfixed32 value = 1;</code>
			 */
			public Builder setValue(int value) {
				bitField0_ |= 0x00000001;
				value_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required sfixed32 value = 1;</code>
			 */
			public Builder clearValue() {
				bitField0_ = (bitField0_ & ~0x00000001);
				value_ = 0;
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:eu.stratosphere.languagebinding.api.java.proto.TupleSize)
		}

		static {
			defaultInstance = new TupleSize(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:eu.stratosphere.languagebinding.api.java.proto.TupleSize)
	}

	public interface ProtoTupleOrBuilder
			extends com.google.protobuf.MessageOrBuilder {

		// required bool atomicType = 2;
		/**
		 * <code>required bool atomicType = 2;</code>
		 */
		boolean hasAtomicType();

		/**
		 * <code>required bool atomicType = 2;</code>
		 */
		boolean getAtomicType();

		// repeated .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue values = 1;
		/**
		 * <code>repeated .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue values = 1;</code>
		 */
		java.util.List<eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue>
				getValuesList();

		/**
		 * <code>repeated .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue values = 1;</code>
		 */
		eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue getValues(int index);

		/**
		 * <code>repeated .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue values = 1;</code>
		 */
		int getValuesCount();

		/**
		 * <code>repeated .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue values = 1;</code>
		 */
		java.util.List<? extends eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValueOrBuilder>
				getValuesOrBuilderList();

		/**
		 * <code>repeated .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue values = 1;</code>
		 */
		eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValueOrBuilder getValuesOrBuilder(
				int index);
	}

	/**
	 * Protobuf type {@code eu.stratosphere.languagebinding.api.java.proto.ProtoTuple}
	 */
	public static final class ProtoTuple extends
			com.google.protobuf.GeneratedMessage
			implements ProtoTupleOrBuilder {
		// Use ProtoTuple.newBuilder() to construct.
		private ProtoTuple(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
			super(builder);
			this.unknownFields = builder.getUnknownFields();
		}

		private ProtoTuple(boolean noInit) {
			this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
		}

		private static final ProtoTuple defaultInstance;

		public static ProtoTuple getDefaultInstance() {
			return defaultInstance;
		}

		public ProtoTuple getDefaultInstanceForType() {
			return defaultInstance;
		}

		private final com.google.protobuf.UnknownFieldSet unknownFields;

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet
				getUnknownFields() {
			return this.unknownFields;
		}

		private ProtoTuple(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			initFields();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields
					= com.google.protobuf.UnknownFieldSet.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
						case 0:
							done = true;
							break;
						default: {
							if (!parseUnknownField(input, unknownFields,
									extensionRegistry, tag)) {
								done = true;
							}
							break;
						}
						case 10: {
							if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
								values_ = new java.util.ArrayList<eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue>();
								mutable_bitField0_ |= 0x00000002;
							}
							values_.add(input.readMessage(eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue.PARSER, extensionRegistry));
							break;
						}
						case 16: {
							bitField0_ |= 0x00000001;
							atomicType_ = input.readBool();
							break;
						}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
						e.getMessage()).setUnfinishedMessage(this);
			} finally {
				if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
					values_ = java.util.Collections.unmodifiableList(values_);
				}
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor
				getDescriptor() {
			return eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.internal_static_eu_stratosphere_languagebinding_api_java_proto_ProtoTuple_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
				internalGetFieldAccessorTable() {
			return eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.internal_static_eu_stratosphere_languagebinding_api_java_proto_ProtoTuple_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.class, eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.Builder.class);
		}

		public static com.google.protobuf.Parser<ProtoTuple> PARSER
				= new com.google.protobuf.AbstractParser<ProtoTuple>() {
					public ProtoTuple parsePartialFrom(
							com.google.protobuf.CodedInputStream input,
							com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
						return new ProtoTuple(input, extensionRegistry);
					}
				};

		@java.lang.Override
		public com.google.protobuf.Parser<ProtoTuple> getParserForType() {
			return PARSER;
		}

		/**
		 * Protobuf enum {@code eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldType}
		 */
		public enum FieldType
				implements com.google.protobuf.ProtocolMessageEnum {
			/**
			 * <code>String = 0;</code>
			 */
			String(0, 0),
			/**
			 * <code>Byte = 1;</code>
			 */
			Byte(1, 1),
			/**
			 * <code>Short = 2;</code>
			 */
			Short(2, 2),
			/**
			 * <code>Integer = 3;</code>
			 */
			Integer(3, 3),
			/**
			 * <code>Long = 4;</code>
			 */
			Long(4, 4),
			/**
			 * <code>Float = 5;</code>
			 */
			Float(5, 5),
			/**
			 * <code>Double = 6;</code>
			 */
			Double(6, 6),
			/**
			 * <code>Boolean = 7;</code>
			 */
			Boolean(7, 7),;

			/**
			 * <code>String = 0;</code>
			 */
			public static final int String_VALUE = 0;
			/**
			 * <code>Byte = 1;</code>
			 */
			public static final int Byte_VALUE = 1;
			/**
			 * <code>Short = 2;</code>
			 */
			public static final int Short_VALUE = 2;
			/**
			 * <code>Integer = 3;</code>
			 */
			public static final int Integer_VALUE = 3;
			/**
			 * <code>Long = 4;</code>
			 */
			public static final int Long_VALUE = 4;
			/**
			 * <code>Float = 5;</code>
			 */
			public static final int Float_VALUE = 5;
			/**
			 * <code>Double = 6;</code>
			 */
			public static final int Double_VALUE = 6;
			/**
			 * <code>Boolean = 7;</code>
			 */
			public static final int Boolean_VALUE = 7;

			public final int getNumber() {
				return value;
			}

			public static FieldType valueOf(int value) {
				switch (value) {
					case 0:
						return String;
					case 1:
						return Byte;
					case 2:
						return Short;
					case 3:
						return Integer;
					case 4:
						return Long;
					case 5:
						return Float;
					case 6:
						return Double;
					case 7:
						return Boolean;
					default:
						return null;
				}
			}

			public static com.google.protobuf.Internal.EnumLiteMap<FieldType>
					internalGetValueMap() {
				return internalValueMap;
			}
			private static com.google.protobuf.Internal.EnumLiteMap<FieldType> internalValueMap
					= new com.google.protobuf.Internal.EnumLiteMap<FieldType>() {
						public FieldType findValueByNumber(int number) {
							return FieldType.valueOf(number);
						}
					};

			public final com.google.protobuf.Descriptors.EnumValueDescriptor
					getValueDescriptor() {
				return getDescriptor().getValues().get(index);
			}

			public final com.google.protobuf.Descriptors.EnumDescriptor
					getDescriptorForType() {
				return getDescriptor();
			}

			public static final com.google.protobuf.Descriptors.EnumDescriptor
					getDescriptor() {
				return eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.getDescriptor().getEnumTypes().get(0);
			}

			private static final FieldType[] VALUES = values();

			public static FieldType valueOf(
					com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
				if (desc.getType() != getDescriptor()) {
					throw new java.lang.IllegalArgumentException(
							"EnumValueDescriptor is not for this type.");
				}
				return VALUES[desc.getIndex()];
			}

			private final int index;
			private final int value;

			private FieldType(int index, int value) {
				this.index = index;
				this.value = value;
			}

			// @@protoc_insertion_point(enum_scope:eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldType)
		}

		public interface FieldValueOrBuilder
				extends com.google.protobuf.MessageOrBuilder {

			// required .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldType fieldType = 1;
			/**
			 * <code>required .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldType fieldType = 1;</code>
			 */
			boolean hasFieldType();

			/**
			 * <code>required .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldType fieldType = 1;</code>
			 */
			eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldType getFieldType();

			// optional string stringVal = 2;
			/**
			 * <code>optional string stringVal = 2;</code>
			 */
			boolean hasStringVal();

			/**
			 * <code>optional string stringVal = 2;</code>
			 */
			java.lang.String getStringVal();

			/**
			 * <code>optional string stringVal = 2;</code>
			 */
			com.google.protobuf.ByteString
					getStringValBytes();

			// optional int32 int32Val = 3;
			/**
			 * <code>optional int32 int32Val = 3;</code>
			 */
			boolean hasInt32Val();

			/**
			 * <code>optional int32 int32Val = 3;</code>
			 */
			int getInt32Val();

			// optional int64 int64Val = 4;
			/**
			 * <code>optional int64 int64Val = 4;</code>
			 */
			boolean hasInt64Val();

			/**
			 * <code>optional int64 int64Val = 4;</code>
			 */
			long getInt64Val();

			// optional double doubleVal = 5;
			/**
			 * <code>optional double doubleVal = 5;</code>
			 */
			boolean hasDoubleVal();

			/**
			 * <code>optional double doubleVal = 5;</code>
			 */
			double getDoubleVal();

			// optional float floatVal = 6;
			/**
			 * <code>optional float floatVal = 6;</code>
			 */
			boolean hasFloatVal();

			/**
			 * <code>optional float floatVal = 6;</code>
			 */
			float getFloatVal();

			// optional bool boolVal = 7;
			/**
			 * <code>optional bool boolVal = 7;</code>
			 */
			boolean hasBoolVal();

			/**
			 * <code>optional bool boolVal = 7;</code>
			 */
			boolean getBoolVal();
		}

		/**
		 * Protobuf type {@code eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue}
		 */
		public static final class FieldValue extends
				com.google.protobuf.GeneratedMessage
				implements FieldValueOrBuilder {
			// Use FieldValue.newBuilder() to construct.
			private FieldValue(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
				super(builder);
				this.unknownFields = builder.getUnknownFields();
			}

			private FieldValue(boolean noInit) {
				this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
			}

			private static final FieldValue defaultInstance;

			public static FieldValue getDefaultInstance() {
				return defaultInstance;
			}

			public FieldValue getDefaultInstanceForType() {
				return defaultInstance;
			}

			private final com.google.protobuf.UnknownFieldSet unknownFields;

			@java.lang.Override
			public final com.google.protobuf.UnknownFieldSet
					getUnknownFields() {
				return this.unknownFields;
			}

			private FieldValue(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				initFields();
				int mutable_bitField0_ = 0;
				com.google.protobuf.UnknownFieldSet.Builder unknownFields
						= com.google.protobuf.UnknownFieldSet.newBuilder();
				try {
					boolean done = false;
					while (!done) {
						int tag = input.readTag();
						switch (tag) {
							case 0:
								done = true;
								break;
							default: {
								if (!parseUnknownField(input, unknownFields,
										extensionRegistry, tag)) {
									done = true;
								}
								break;
							}
							case 8: {
								int rawValue = input.readEnum();
								eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldType value = eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldType.valueOf(rawValue);
								if (value == null) {
									unknownFields.mergeVarintField(1, rawValue);
								} else {
									bitField0_ |= 0x00000001;
									fieldType_ = value;
								}
								break;
							}
							case 18: {
								bitField0_ |= 0x00000002;
								stringVal_ = input.readBytes();
								break;
							}
							case 24: {
								bitField0_ |= 0x00000004;
								int32Val_ = input.readInt32();
								break;
							}
							case 32: {
								bitField0_ |= 0x00000008;
								int64Val_ = input.readInt64();
								break;
							}
							case 41: {
								bitField0_ |= 0x00000010;
								doubleVal_ = input.readDouble();
								break;
							}
							case 53: {
								bitField0_ |= 0x00000020;
								floatVal_ = input.readFloat();
								break;
							}
							case 56: {
								bitField0_ |= 0x00000040;
								boolVal_ = input.readBool();
								break;
							}
						}
					}
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					throw e.setUnfinishedMessage(this);
				} catch (java.io.IOException e) {
					throw new com.google.protobuf.InvalidProtocolBufferException(
							e.getMessage()).setUnfinishedMessage(this);
				} finally {
					this.unknownFields = unknownFields.build();
					makeExtensionsImmutable();
				}
			}

			public static final com.google.protobuf.Descriptors.Descriptor
					getDescriptor() {
				return eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.internal_static_eu_stratosphere_languagebinding_api_java_proto_ProtoTuple_FieldValue_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
					internalGetFieldAccessorTable() {
				return eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.internal_static_eu_stratosphere_languagebinding_api_java_proto_ProtoTuple_FieldValue_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue.class, eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue.Builder.class);
			}

			public static com.google.protobuf.Parser<FieldValue> PARSER
					= new com.google.protobuf.AbstractParser<FieldValue>() {
						public FieldValue parsePartialFrom(
								com.google.protobuf.CodedInputStream input,
								com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
							return new FieldValue(input, extensionRegistry);
						}
					};

			@java.lang.Override
			public com.google.protobuf.Parser<FieldValue> getParserForType() {
				return PARSER;
			}

			private int bitField0_;
			// required .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldType fieldType = 1;
			public static final int FIELDTYPE_FIELD_NUMBER = 1;
			private eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldType fieldType_;

			/**
			 * <code>required .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldType fieldType = 1;</code>
			 */
			public boolean hasFieldType() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <code>required .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldType fieldType = 1;</code>
			 */
			public eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldType getFieldType() {
				return fieldType_;
			}

			// optional string stringVal = 2;
			public static final int STRINGVAL_FIELD_NUMBER = 2;
			private java.lang.Object stringVal_;

			/**
			 * <code>optional string stringVal = 2;</code>
			 */
			public boolean hasStringVal() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			/**
			 * <code>optional string stringVal = 2;</code>
			 */
			public java.lang.String getStringVal() {
				java.lang.Object ref = stringVal_;
				if (ref instanceof java.lang.String) {
					return (java.lang.String) ref;
				} else {
					com.google.protobuf.ByteString bs
							= (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						stringVal_ = s;
					}
					return s;
				}
			}

			/**
			 * <code>optional string stringVal = 2;</code>
			 */
			public com.google.protobuf.ByteString
					getStringValBytes() {
				java.lang.Object ref = stringVal_;
				if (ref instanceof java.lang.String) {
					com.google.protobuf.ByteString b
							= com.google.protobuf.ByteString.copyFromUtf8(
									(java.lang.String) ref);
					stringVal_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			// optional int32 int32Val = 3;
			public static final int INT32VAL_FIELD_NUMBER = 3;
			private int int32Val_;

			/**
			 * <code>optional int32 int32Val = 3;</code>
			 */
			public boolean hasInt32Val() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			/**
			 * <code>optional int32 int32Val = 3;</code>
			 */
			public int getInt32Val() {
				return int32Val_;
			}

			// optional int64 int64Val = 4;
			public static final int INT64VAL_FIELD_NUMBER = 4;
			private long int64Val_;

			/**
			 * <code>optional int64 int64Val = 4;</code>
			 */
			public boolean hasInt64Val() {
				return ((bitField0_ & 0x00000008) == 0x00000008);
			}

			/**
			 * <code>optional int64 int64Val = 4;</code>
			 */
			public long getInt64Val() {
				return int64Val_;
			}

			// optional double doubleVal = 5;
			public static final int DOUBLEVAL_FIELD_NUMBER = 5;
			private double doubleVal_;

			/**
			 * <code>optional double doubleVal = 5;</code>
			 */
			public boolean hasDoubleVal() {
				return ((bitField0_ & 0x00000010) == 0x00000010);
			}

			/**
			 * <code>optional double doubleVal = 5;</code>
			 */
			public double getDoubleVal() {
				return doubleVal_;
			}

			// optional float floatVal = 6;
			public static final int FLOATVAL_FIELD_NUMBER = 6;
			private float floatVal_;

			/**
			 * <code>optional float floatVal = 6;</code>
			 */
			public boolean hasFloatVal() {
				return ((bitField0_ & 0x00000020) == 0x00000020);
			}

			/**
			 * <code>optional float floatVal = 6;</code>
			 */
			public float getFloatVal() {
				return floatVal_;
			}

			// optional bool boolVal = 7;
			public static final int BOOLVAL_FIELD_NUMBER = 7;
			private boolean boolVal_;

			/**
			 * <code>optional bool boolVal = 7;</code>
			 */
			public boolean hasBoolVal() {
				return ((bitField0_ & 0x00000040) == 0x00000040);
			}

			/**
			 * <code>optional bool boolVal = 7;</code>
			 */
			public boolean getBoolVal() {
				return boolVal_;
			}

			private void initFields() {
				fieldType_ = eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldType.String;
				stringVal_ = "";
				int32Val_ = 0;
				int64Val_ = 0L;
				doubleVal_ = 0D;
				floatVal_ = 0F;
				boolVal_ = false;
			}
			private byte memoizedIsInitialized = -1;

			public final boolean isInitialized() {
				byte isInitialized = memoizedIsInitialized;
				if (isInitialized != -1) {
					return isInitialized == 1;
				}

				if (!hasFieldType()) {
					memoizedIsInitialized = 0;
					return false;
				}
				memoizedIsInitialized = 1;
				return true;
			}

			public void writeTo(com.google.protobuf.CodedOutputStream output)
					throws java.io.IOException {
				getSerializedSize();
				if (((bitField0_ & 0x00000001) == 0x00000001)) {
					output.writeEnum(1, fieldType_.getNumber());
				}
				if (((bitField0_ & 0x00000002) == 0x00000002)) {
					output.writeBytes(2, getStringValBytes());
				}
				if (((bitField0_ & 0x00000004) == 0x00000004)) {
					output.writeInt32(3, int32Val_);
				}
				if (((bitField0_ & 0x00000008) == 0x00000008)) {
					output.writeInt64(4, int64Val_);
				}
				if (((bitField0_ & 0x00000010) == 0x00000010)) {
					output.writeDouble(5, doubleVal_);
				}
				if (((bitField0_ & 0x00000020) == 0x00000020)) {
					output.writeFloat(6, floatVal_);
				}
				if (((bitField0_ & 0x00000040) == 0x00000040)) {
					output.writeBool(7, boolVal_);
				}
				getUnknownFields().writeTo(output);
			}

			private int memoizedSerializedSize = -1;

			public int getSerializedSize() {
				int size = memoizedSerializedSize;
				if (size != -1) {
					return size;
				}

				size = 0;
				if (((bitField0_ & 0x00000001) == 0x00000001)) {
					size += com.google.protobuf.CodedOutputStream
							.computeEnumSize(1, fieldType_.getNumber());
				}
				if (((bitField0_ & 0x00000002) == 0x00000002)) {
					size += com.google.protobuf.CodedOutputStream
							.computeBytesSize(2, getStringValBytes());
				}
				if (((bitField0_ & 0x00000004) == 0x00000004)) {
					size += com.google.protobuf.CodedOutputStream
							.computeInt32Size(3, int32Val_);
				}
				if (((bitField0_ & 0x00000008) == 0x00000008)) {
					size += com.google.protobuf.CodedOutputStream
							.computeInt64Size(4, int64Val_);
				}
				if (((bitField0_ & 0x00000010) == 0x00000010)) {
					size += com.google.protobuf.CodedOutputStream
							.computeDoubleSize(5, doubleVal_);
				}
				if (((bitField0_ & 0x00000020) == 0x00000020)) {
					size += com.google.protobuf.CodedOutputStream
							.computeFloatSize(6, floatVal_);
				}
				if (((bitField0_ & 0x00000040) == 0x00000040)) {
					size += com.google.protobuf.CodedOutputStream
							.computeBoolSize(7, boolVal_);
				}
				size += getUnknownFields().getSerializedSize();
				memoizedSerializedSize = size;
				return size;
			}

			private static final long serialVersionUID = 0L;

			@java.lang.Override
			protected java.lang.Object writeReplace()
					throws java.io.ObjectStreamException {
				return super.writeReplace();
			}

			public static eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue parseFrom(
					com.google.protobuf.ByteString data)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data);
			}

			public static eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue parseFrom(
					com.google.protobuf.ByteString data,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data, extensionRegistry);
			}

			public static eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue parseFrom(byte[] data)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data);
			}

			public static eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue parseFrom(
					byte[] data,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data, extensionRegistry);
			}

			public static eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue parseFrom(java.io.InputStream input)
					throws java.io.IOException {
				return PARSER.parseFrom(input);
			}

			public static eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue parseFrom(
					java.io.InputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				return PARSER.parseFrom(input, extensionRegistry);
			}

			public static eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue parseDelimitedFrom(java.io.InputStream input)
					throws java.io.IOException {
				return PARSER.parseDelimitedFrom(input);
			}

			public static eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue parseDelimitedFrom(
					java.io.InputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				return PARSER.parseDelimitedFrom(input, extensionRegistry);
			}

			public static eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue parseFrom(
					com.google.protobuf.CodedInputStream input)
					throws java.io.IOException {
				return PARSER.parseFrom(input);
			}

			public static eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue parseFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				return PARSER.parseFrom(input, extensionRegistry);
			}

			public static Builder newBuilder() {
				return Builder.create();
			}

			public Builder newBuilderForType() {
				return newBuilder();
			}

			public static Builder newBuilder(eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue prototype) {
				return newBuilder().mergeFrom(prototype);
			}

			public Builder toBuilder() {
				return newBuilder(this);
			}

			@java.lang.Override
			protected Builder newBuilderForType(
					com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				Builder builder = new Builder(parent);
				return builder;
			}

			/**
			 * Protobuf type {@code eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue}
			 */
			public static final class Builder extends
					com.google.protobuf.GeneratedMessage.Builder<Builder>
					implements eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValueOrBuilder {
				public static final com.google.protobuf.Descriptors.Descriptor
						getDescriptor() {
					return eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.internal_static_eu_stratosphere_languagebinding_api_java_proto_ProtoTuple_FieldValue_descriptor;
				}

				protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
						internalGetFieldAccessorTable() {
					return eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.internal_static_eu_stratosphere_languagebinding_api_java_proto_ProtoTuple_FieldValue_fieldAccessorTable
							.ensureFieldAccessorsInitialized(
									eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue.class, eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue.Builder.class);
				}

				// Construct using eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue.newBuilder()
				private Builder() {
					maybeForceBuilderInitialization();
				}

				private Builder(
						com.google.protobuf.GeneratedMessage.BuilderParent parent) {
					super(parent);
					maybeForceBuilderInitialization();
				}

				private void maybeForceBuilderInitialization() {
					if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					}
				}

				private static Builder create() {
					return new Builder();
				}

				public Builder clear() {
					super.clear();
					fieldType_ = eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldType.String;
					bitField0_ = (bitField0_ & ~0x00000001);
					stringVal_ = "";
					bitField0_ = (bitField0_ & ~0x00000002);
					int32Val_ = 0;
					bitField0_ = (bitField0_ & ~0x00000004);
					int64Val_ = 0L;
					bitField0_ = (bitField0_ & ~0x00000008);
					doubleVal_ = 0D;
					bitField0_ = (bitField0_ & ~0x00000010);
					floatVal_ = 0F;
					bitField0_ = (bitField0_ & ~0x00000020);
					boolVal_ = false;
					bitField0_ = (bitField0_ & ~0x00000040);
					return this;
				}

				public Builder clone() {
					return create().mergeFrom(buildPartial());
				}

				public com.google.protobuf.Descriptors.Descriptor
						getDescriptorForType() {
					return eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.internal_static_eu_stratosphere_languagebinding_api_java_proto_ProtoTuple_FieldValue_descriptor;
				}

				public eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue getDefaultInstanceForType() {
					return eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue.getDefaultInstance();
				}

				public eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue build() {
					eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue result = buildPartial();
					if (!result.isInitialized()) {
						throw newUninitializedMessageException(result);
					}
					return result;
				}

				public eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue buildPartial() {
					eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue result = new eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue(this);
					int from_bitField0_ = bitField0_;
					int to_bitField0_ = 0;
					if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
						to_bitField0_ |= 0x00000001;
					}
					result.fieldType_ = fieldType_;
					if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
						to_bitField0_ |= 0x00000002;
					}
					result.stringVal_ = stringVal_;
					if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
						to_bitField0_ |= 0x00000004;
					}
					result.int32Val_ = int32Val_;
					if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
						to_bitField0_ |= 0x00000008;
					}
					result.int64Val_ = int64Val_;
					if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
						to_bitField0_ |= 0x00000010;
					}
					result.doubleVal_ = doubleVal_;
					if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
						to_bitField0_ |= 0x00000020;
					}
					result.floatVal_ = floatVal_;
					if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
						to_bitField0_ |= 0x00000040;
					}
					result.boolVal_ = boolVal_;
					result.bitField0_ = to_bitField0_;
					onBuilt();
					return result;
				}

				public Builder mergeFrom(com.google.protobuf.Message other) {
					if (other instanceof eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue) {
						return mergeFrom((eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue) other);
					} else {
						super.mergeFrom(other);
						return this;
					}
				}

				public Builder mergeFrom(eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue other) {
					if (other == eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue.getDefaultInstance()) {
						return this;
					}
					if (other.hasFieldType()) {
						setFieldType(other.getFieldType());
					}
					if (other.hasStringVal()) {
						bitField0_ |= 0x00000002;
						stringVal_ = other.stringVal_;
						onChanged();
					}
					if (other.hasInt32Val()) {
						setInt32Val(other.getInt32Val());
					}
					if (other.hasInt64Val()) {
						setInt64Val(other.getInt64Val());
					}
					if (other.hasDoubleVal()) {
						setDoubleVal(other.getDoubleVal());
					}
					if (other.hasFloatVal()) {
						setFloatVal(other.getFloatVal());
					}
					if (other.hasBoolVal()) {
						setBoolVal(other.getBoolVal());
					}
					this.mergeUnknownFields(other.getUnknownFields());
					return this;
				}

				public final boolean isInitialized() {
					if (!hasFieldType()) {

						return false;
					}
					return true;
				}

				public Builder mergeFrom(
						com.google.protobuf.CodedInputStream input,
						com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
					eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue parsedMessage = null;
					try {
						parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
					} catch (com.google.protobuf.InvalidProtocolBufferException e) {
						parsedMessage = (eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue) e.getUnfinishedMessage();
						throw e;
					} finally {
						if (parsedMessage != null) {
							mergeFrom(parsedMessage);
						}
					}
					return this;
				}
				private int bitField0_;

				// required .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldType fieldType = 1;
				private eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldType fieldType_ = eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldType.String;

				/**
				 * <code>required .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldType fieldType = 1;</code>
				 */
				public boolean hasFieldType() {
					return ((bitField0_ & 0x00000001) == 0x00000001);
				}

				/**
				 * <code>required .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldType fieldType = 1;</code>
				 */
				public eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldType getFieldType() {
					return fieldType_;
				}

				/**
				 * <code>required .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldType fieldType = 1;</code>
				 */
				public Builder setFieldType(eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldType value) {
					if (value == null) {
						throw new NullPointerException();
					}
					bitField0_ |= 0x00000001;
					fieldType_ = value;
					onChanged();
					return this;
				}

				/**
				 * <code>required .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldType fieldType = 1;</code>
				 */
				public Builder clearFieldType() {
					bitField0_ = (bitField0_ & ~0x00000001);
					fieldType_ = eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldType.String;
					onChanged();
					return this;
				}

				// optional string stringVal = 2;
				private java.lang.Object stringVal_ = "";

				/**
				 * <code>optional string stringVal = 2;</code>
				 */
				public boolean hasStringVal() {
					return ((bitField0_ & 0x00000002) == 0x00000002);
				}

				/**
				 * <code>optional string stringVal = 2;</code>
				 */
				public java.lang.String getStringVal() {
					java.lang.Object ref = stringVal_;
					if (!(ref instanceof java.lang.String)) {
						java.lang.String s = ((com.google.protobuf.ByteString) ref)
								.toStringUtf8();
						stringVal_ = s;
						return s;
					} else {
						return (java.lang.String) ref;
					}
				}

				/**
				 * <code>optional string stringVal = 2;</code>
				 */
				public com.google.protobuf.ByteString
						getStringValBytes() {
					java.lang.Object ref = stringVal_;
					if (ref instanceof String) {
						com.google.protobuf.ByteString b
								= com.google.protobuf.ByteString.copyFromUtf8(
										(java.lang.String) ref);
						stringVal_ = b;
						return b;
					} else {
						return (com.google.protobuf.ByteString) ref;
					}
				}

				/**
				 * <code>optional string stringVal = 2;</code>
				 */
				public Builder setStringVal(
						java.lang.String value) {
					if (value == null) {
						//MODIFICATION
						value = "";
					}
					bitField0_ |= 0x00000002;
					stringVal_ = value;
					onChanged();
					return this;
				}

				/**
				 * <code>optional string stringVal = 2;</code>
				 */
				public Builder clearStringVal() {
					bitField0_ = (bitField0_ & ~0x00000002);
					stringVal_ = getDefaultInstance().getStringVal();
					onChanged();
					return this;
				}

				/**
				 * <code>optional string stringVal = 2;</code>
				 */
				public Builder setStringValBytes(
						com.google.protobuf.ByteString value) {
					if (value == null) {
						throw new NullPointerException();
					}
					bitField0_ |= 0x00000002;
					stringVal_ = value;
					onChanged();
					return this;
				}

				// optional int32 int32Val = 3;
				private int int32Val_;

				/**
				 * <code>optional int32 int32Val = 3;</code>
				 */
				public boolean hasInt32Val() {
					return ((bitField0_ & 0x00000004) == 0x00000004);
				}

				/**
				 * <code>optional int32 int32Val = 3;</code>
				 */
				public int getInt32Val() {
					return int32Val_;
				}

				/**
				 * <code>optional int32 int32Val = 3;</code>
				 */
				public Builder setInt32Val(int value) {
					bitField0_ |= 0x00000004;
					int32Val_ = value;
					onChanged();
					return this;
				}

				/**
				 * <code>optional int32 int32Val = 3;</code>
				 */
				public Builder clearInt32Val() {
					bitField0_ = (bitField0_ & ~0x00000004);
					int32Val_ = 0;
					onChanged();
					return this;
				}

				// optional int64 int64Val = 4;
				private long int64Val_;

				/**
				 * <code>optional int64 int64Val = 4;</code>
				 */
				public boolean hasInt64Val() {
					return ((bitField0_ & 0x00000008) == 0x00000008);
				}

				/**
				 * <code>optional int64 int64Val = 4;</code>
				 */
				public long getInt64Val() {
					return int64Val_;
				}

				/**
				 * <code>optional int64 int64Val = 4;</code>
				 */
				public Builder setInt64Val(long value) {
					bitField0_ |= 0x00000008;
					int64Val_ = value;
					onChanged();
					return this;
				}

				/**
				 * <code>optional int64 int64Val = 4;</code>
				 */
				public Builder clearInt64Val() {
					bitField0_ = (bitField0_ & ~0x00000008);
					int64Val_ = 0L;
					onChanged();
					return this;
				}

				// optional double doubleVal = 5;
				private double doubleVal_;

				/**
				 * <code>optional double doubleVal = 5;</code>
				 */
				public boolean hasDoubleVal() {
					return ((bitField0_ & 0x00000010) == 0x00000010);
				}

				/**
				 * <code>optional double doubleVal = 5;</code>
				 */
				public double getDoubleVal() {
					return doubleVal_;
				}

				/**
				 * <code>optional double doubleVal = 5;</code>
				 */
				public Builder setDoubleVal(double value) {
					bitField0_ |= 0x00000010;
					doubleVal_ = value;
					onChanged();
					return this;
				}

				/**
				 * <code>optional double doubleVal = 5;</code>
				 */
				public Builder clearDoubleVal() {
					bitField0_ = (bitField0_ & ~0x00000010);
					doubleVal_ = 0D;
					onChanged();
					return this;
				}

				// optional float floatVal = 6;
				private float floatVal_;

				/**
				 * <code>optional float floatVal = 6;</code>
				 */
				public boolean hasFloatVal() {
					return ((bitField0_ & 0x00000020) == 0x00000020);
				}

				/**
				 * <code>optional float floatVal = 6;</code>
				 */
				public float getFloatVal() {
					return floatVal_;
				}

				/**
				 * <code>optional float floatVal = 6;</code>
				 */
				public Builder setFloatVal(float value) {
					bitField0_ |= 0x00000020;
					floatVal_ = value;
					onChanged();
					return this;
				}

				/**
				 * <code>optional float floatVal = 6;</code>
				 */
				public Builder clearFloatVal() {
					bitField0_ = (bitField0_ & ~0x00000020);
					floatVal_ = 0F;
					onChanged();
					return this;
				}

				// optional bool boolVal = 7;
				private boolean boolVal_;

				/**
				 * <code>optional bool boolVal = 7;</code>
				 */
				public boolean hasBoolVal() {
					return ((bitField0_ & 0x00000040) == 0x00000040);
				}

				/**
				 * <code>optional bool boolVal = 7;</code>
				 */
				public boolean getBoolVal() {
					return boolVal_;
				}

				/**
				 * <code>optional bool boolVal = 7;</code>
				 */
				public Builder setBoolVal(boolean value) {
					bitField0_ |= 0x00000040;
					boolVal_ = value;
					onChanged();
					return this;
				}

				/**
				 * <code>optional bool boolVal = 7;</code>
				 */
				public Builder clearBoolVal() {
					bitField0_ = (bitField0_ & ~0x00000040);
					boolVal_ = false;
					onChanged();
					return this;
				}

				// @@protoc_insertion_point(builder_scope:eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue)
			}

			static {
				defaultInstance = new FieldValue(true);
				defaultInstance.initFields();
			}

			// @@protoc_insertion_point(class_scope:eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue)
		}

		private int bitField0_;
		// required bool atomicType = 2;
		public static final int ATOMICTYPE_FIELD_NUMBER = 2;
		private boolean atomicType_;

		/**
		 * <code>required bool atomicType = 2;</code>
		 */
		public boolean hasAtomicType() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		/**
		 * <code>required bool atomicType = 2;</code>
		 */
		public boolean getAtomicType() {
			return atomicType_;
		}

		// repeated .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue values = 1;
		public static final int VALUES_FIELD_NUMBER = 1;
		private java.util.List<eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue> values_;

		/**
		 * <code>repeated .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue values = 1;</code>
		 */
		public java.util.List<eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue> getValuesList() {
			return values_;
		}

		/**
		 * <code>repeated .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue values = 1;</code>
		 */
		public java.util.List<? extends eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValueOrBuilder>
				getValuesOrBuilderList() {
			return values_;
		}

		/**
		 * <code>repeated .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue values = 1;</code>
		 */
		public int getValuesCount() {
			return values_.size();
		}

		/**
		 * <code>repeated .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue values = 1;</code>
		 */
		public eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue getValues(int index) {
			return values_.get(index);
		}

		/**
		 * <code>repeated .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue values = 1;</code>
		 */
		public eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValueOrBuilder getValuesOrBuilder(
				int index) {
			return values_.get(index);
		}

		private void initFields() {
			atomicType_ = false;
			values_ = java.util.Collections.emptyList();
		}
		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1) {
				return isInitialized == 1;
			}

			if (!hasAtomicType()) {
				memoizedIsInitialized = 0;
				return false;
			}
			for (int i = 0; i < getValuesCount(); i++) {
				if (!getValues(i).isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			for (int i = 0; i < values_.size(); i++) {
				output.writeMessage(1, values_.get(i));
			}
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeBool(2, atomicType_);
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1) {
				return size;
			}

			size = 0;
			for (int i = 0; i < values_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(1, values_.get(i));
			}
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBoolSize(2, atomicType_);
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input);
		}

		public static eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input, extensionRegistry);
		}

		public static eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code eu.stratosphere.languagebinding.api.java.proto.ProtoTuple}
		 */
		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTupleOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor
					getDescriptor() {
				return eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.internal_static_eu_stratosphere_languagebinding_api_java_proto_ProtoTuple_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
					internalGetFieldAccessorTable() {
				return eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.internal_static_eu_stratosphere_languagebinding_api_java_proto_ProtoTuple_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.class, eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.Builder.class);
			}

			// Construct using eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
					com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getValuesFieldBuilder();
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				atomicType_ = false;
				bitField0_ = (bitField0_ & ~0x00000001);
				if (valuesBuilder_ == null) {
					values_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000002);
				} else {
					valuesBuilder_.clear();
				}
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor
					getDescriptorForType() {
				return eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.internal_static_eu_stratosphere_languagebinding_api_java_proto_ProtoTuple_descriptor;
			}

			public eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple getDefaultInstanceForType() {
				return eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.getDefaultInstance();
			}

			public eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple build() {
				eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple buildPartial() {
				eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple result = new eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.atomicType_ = atomicType_;
				if (valuesBuilder_ == null) {
					if (((bitField0_ & 0x00000002) == 0x00000002)) {
						values_ = java.util.Collections.unmodifiableList(values_);
						bitField0_ = (bitField0_ & ~0x00000002);
					}
					result.values_ = values_;
				} else {
					result.values_ = valuesBuilder_.build();
				}
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple) {
					return mergeFrom((eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple other) {
				if (other == eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.getDefaultInstance()) {
					return this;
				}
				if (other.hasAtomicType()) {
					setAtomicType(other.getAtomicType());
				}
				if (valuesBuilder_ == null) {
					if (!other.values_.isEmpty()) {
						if (values_.isEmpty()) {
							values_ = other.values_;
							bitField0_ = (bitField0_ & ~0x00000002);
						} else {
							ensureValuesIsMutable();
							values_.addAll(other.values_);
						}
						onChanged();
					}
				} else {
					if (!other.values_.isEmpty()) {
						if (valuesBuilder_.isEmpty()) {
							valuesBuilder_.dispose();
							valuesBuilder_ = null;
							values_ = other.values_;
							bitField0_ = (bitField0_ & ~0x00000002);
							valuesBuilder_
									= com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders
									? getValuesFieldBuilder() : null;
						} else {
							valuesBuilder_.addAllMessages(other.values_);
						}
					}
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasAtomicType()) {

					return false;
				}
				for (int i = 0; i < getValuesCount(); i++) {
					if (!getValues(i).isInitialized()) {

						return false;
					}
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple) e.getUnfinishedMessage();
					throw e;
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}
			private int bitField0_;

			// required bool atomicType = 2;
			private boolean atomicType_;

			/**
			 * <code>required bool atomicType = 2;</code>
			 */
			public boolean hasAtomicType() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <code>required bool atomicType = 2;</code>
			 */
			public boolean getAtomicType() {
				return atomicType_;
			}

			/**
			 * <code>required bool atomicType = 2;</code>
			 */
			public Builder setAtomicType(boolean value) {
				bitField0_ |= 0x00000001;
				atomicType_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required bool atomicType = 2;</code>
			 */
			public Builder clearAtomicType() {
				bitField0_ = (bitField0_ & ~0x00000001);
				atomicType_ = false;
				onChanged();
				return this;
			}

			// repeated .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue values = 1;
			private java.util.List<eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue> values_
					= java.util.Collections.emptyList();

			private void ensureValuesIsMutable() {
				if (!((bitField0_ & 0x00000002) == 0x00000002)) {
					values_ = new java.util.ArrayList<eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue>(values_);
					bitField0_ |= 0x00000002;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilder<
          eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue, eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue.Builder, eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValueOrBuilder> valuesBuilder_;

			/**
			 * <code>repeated .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue values = 1;</code>
			 */
			public java.util.List<eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue> getValuesList() {
				if (valuesBuilder_ == null) {
					return java.util.Collections.unmodifiableList(values_);
				} else {
					return valuesBuilder_.getMessageList();
				}
			}

			/**
			 * <code>repeated .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue values = 1;</code>
			 */
			public int getValuesCount() {
				if (valuesBuilder_ == null) {
					return values_.size();
				} else {
					return valuesBuilder_.getCount();
				}
			}

			/**
			 * <code>repeated .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue values = 1;</code>
			 */
			public eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue getValues(int index) {
				if (valuesBuilder_ == null) {
					return values_.get(index);
				} else {
					return valuesBuilder_.getMessage(index);
				}
			}

			/**
			 * <code>repeated .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue values = 1;</code>
			 */
			public Builder setValues(
					int index, eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue value) {
				if (valuesBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureValuesIsMutable();
					values_.set(index, value);
					onChanged();
				} else {
					valuesBuilder_.setMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue values = 1;</code>
			 */
			public Builder setValues(
					int index, eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue.Builder builderForValue) {
				if (valuesBuilder_ == null) {
					ensureValuesIsMutable();
					values_.set(index, builderForValue.build());
					onChanged();
				} else {
					valuesBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue values = 1;</code>
			 */
			public Builder addValues(eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue value) {
				if (valuesBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureValuesIsMutable();
					values_.add(value);
					onChanged();
				} else {
					valuesBuilder_.addMessage(value);
				}
				return this;
			}

			/**
			 * <code>repeated .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue values = 1;</code>
			 */
			public Builder addValues(
					int index, eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue value) {
				if (valuesBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureValuesIsMutable();
					values_.add(index, value);
					onChanged();
				} else {
					valuesBuilder_.addMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue values = 1;</code>
			 */
			public Builder addValues(
					eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue.Builder builderForValue) {
				if (valuesBuilder_ == null) {
					ensureValuesIsMutable();
					values_.add(builderForValue.build());
					onChanged();
				} else {
					valuesBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue values = 1;</code>
			 */
			public Builder addValues(
					int index, eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue.Builder builderForValue) {
				if (valuesBuilder_ == null) {
					ensureValuesIsMutable();
					values_.add(index, builderForValue.build());
					onChanged();
				} else {
					valuesBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue values = 1;</code>
			 */
			public Builder addAllValues(
					java.lang.Iterable<? extends eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue> values) {
				if (valuesBuilder_ == null) {
					ensureValuesIsMutable();
					super.addAll(values, values_);
					onChanged();
				} else {
					valuesBuilder_.addAllMessages(values);
				}
				return this;
			}

			/**
			 * <code>repeated .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue values = 1;</code>
			 */
			public Builder clearValues() {
				if (valuesBuilder_ == null) {
					values_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000002);
					onChanged();
				} else {
					valuesBuilder_.clear();
				}
				return this;
			}

			/**
			 * <code>repeated .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue values = 1;</code>
			 */
			public Builder removeValues(int index) {
				if (valuesBuilder_ == null) {
					ensureValuesIsMutable();
					values_.remove(index);
					onChanged();
				} else {
					valuesBuilder_.remove(index);
				}
				return this;
			}

			/**
			 * <code>repeated .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue values = 1;</code>
			 */
			public eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue.Builder getValuesBuilder(
					int index) {
				return getValuesFieldBuilder().getBuilder(index);
			}

			/**
			 * <code>repeated .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue values = 1;</code>
			 */
			public eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValueOrBuilder getValuesOrBuilder(
					int index) {
				if (valuesBuilder_ == null) {
					return values_.get(index);
				} else {
					return valuesBuilder_.getMessageOrBuilder(index);
				}
			}

			/**
			 * <code>repeated .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue values = 1;</code>
			 */
			public java.util.List<? extends eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValueOrBuilder>
					getValuesOrBuilderList() {
				if (valuesBuilder_ != null) {
					return valuesBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(values_);
				}
			}

			/**
			 * <code>repeated .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue values = 1;</code>
			 */
			public eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue.Builder addValuesBuilder() {
				return getValuesFieldBuilder().addBuilder(
						eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue.getDefaultInstance());
			}

			/**
			 * <code>repeated .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue values = 1;</code>
			 */
			public eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue.Builder addValuesBuilder(
					int index) {
				return getValuesFieldBuilder().addBuilder(
						index, eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue.getDefaultInstance());
			}

			/**
			 * <code>repeated .eu.stratosphere.languagebinding.api.java.proto.ProtoTuple.FieldValue values = 1;</code>
			 */
			public java.util.List<eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue.Builder>
					getValuesBuilderList() {
				return getValuesFieldBuilder().getBuilderList();
			}

			private com.google.protobuf.RepeatedFieldBuilder<
          eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue, eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue.Builder, eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValueOrBuilder>
					getValuesFieldBuilder() {
				if (valuesBuilder_ == null) {
					valuesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue, eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValue.Builder, eu.stratosphere.languagebinding.api.java.proto.ProtocolTuple.ProtoTuple.FieldValueOrBuilder>(
							values_,
							((bitField0_ & 0x00000002) == 0x00000002),
							getParentForChildren(),
							isClean());
					values_ = null;
				}
				return valuesBuilder_;
			}

			// @@protoc_insertion_point(builder_scope:eu.stratosphere.languagebinding.api.java.proto.ProtoTuple)
		}

		static {
			defaultInstance = new ProtoTuple(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:eu.stratosphere.languagebinding.api.java.proto.ProtoTuple)
	}

	private static com.google.protobuf.Descriptors.Descriptor internal_static_eu_stratosphere_languagebinding_api_java_proto_TupleSize_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_eu_stratosphere_languagebinding_api_java_proto_TupleSize_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_eu_stratosphere_languagebinding_api_java_proto_ProtoTuple_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_eu_stratosphere_languagebinding_api_java_proto_ProtoTuple_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_eu_stratosphere_languagebinding_api_java_proto_ProtoTuple_FieldValue_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_eu_stratosphere_languagebinding_api_java_proto_ProtoTuple_FieldValue_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor
			getDescriptor() {
		return descriptor;
	}
	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

	static {
		java.lang.String[] descriptorData = {
			"\n\020ProtoTuple.proto\022.eu.stratosphere.lang"
			+ "uagebinding.api.java.proto\"\032\n\tTupleSize\022"
			+ "\r\n\005value\030\001 \002(\017\"\265\003\n\nProtoTuple\022\022\n\natomicT"
			+ "ype\030\002 \002(\010\022U\n\006values\030\001 \003(\0132E.eu.stratosph"
			+ "ere.languagebinding.api.java.proto.Proto"
			+ "Tuple.FieldValue\032\322\001\n\nFieldValue\022W\n\tfield"
			+ "Type\030\001 \002(\0162D.eu.stratosphere.languagebin"
			+ "ding.api.java.proto.ProtoTuple.FieldType"
			+ "\022\021\n\tstringVal\030\002 \001(\t\022\020\n\010int32Val\030\003 \001(\005\022\020\n"
			+ "\010int64Val\030\004 \001(\003\022\021\n\tdoubleVal\030\005 \001(\001\022\020\n\010fl",
			"oatVal\030\006 \001(\002\022\017\n\007boolVal\030\007 \001(\010\"g\n\tFieldTy"
			+ "pe\022\n\n\006String\020\000\022\010\n\004Byte\020\001\022\t\n\005Short\020\002\022\013\n\007I"
			+ "nteger\020\003\022\010\n\004Long\020\004\022\t\n\005Float\020\005\022\n\n\006Double\020"
			+ "\006\022\013\n\007Boolean\020\007B\017B\rProtocolTuple"
		};
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner
				= new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
					public com.google.protobuf.ExtensionRegistry assignDescriptors(
							com.google.protobuf.Descriptors.FileDescriptor root) {
								descriptor = root;
								internal_static_eu_stratosphere_languagebinding_api_java_proto_TupleSize_descriptor
								= getDescriptor().getMessageTypes().get(0);
								internal_static_eu_stratosphere_languagebinding_api_java_proto_TupleSize_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
										internal_static_eu_stratosphere_languagebinding_api_java_proto_TupleSize_descriptor,
										new java.lang.String[]{"Value",});
								internal_static_eu_stratosphere_languagebinding_api_java_proto_ProtoTuple_descriptor
								= getDescriptor().getMessageTypes().get(1);
								internal_static_eu_stratosphere_languagebinding_api_java_proto_ProtoTuple_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
										internal_static_eu_stratosphere_languagebinding_api_java_proto_ProtoTuple_descriptor,
										new java.lang.String[]{"AtomicType", "Values",});
								internal_static_eu_stratosphere_languagebinding_api_java_proto_ProtoTuple_FieldValue_descriptor
								= internal_static_eu_stratosphere_languagebinding_api_java_proto_ProtoTuple_descriptor.getNestedTypes().get(0);
								internal_static_eu_stratosphere_languagebinding_api_java_proto_ProtoTuple_FieldValue_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
										internal_static_eu_stratosphere_languagebinding_api_java_proto_ProtoTuple_FieldValue_descriptor,
										new java.lang.String[]{"FieldType", "StringVal", "Int32Val", "Int64Val", "DoubleVal", "FloatVal", "BoolVal",});
								return null;
							}
				};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[]{}, assigner);
	}

  // @@protoc_insertion_point(outer_class_scope)
}
