######################################################################################################################
# Copyright (C) 2010-2013 by the Stratosphere project (http://stratosphere.eu)
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
# an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
######################################################################################################################
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProtoTuple.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
    name='ProtoTuple.proto',
    package='eu.stratosphere.languagebinding.proto',
    serialized_pb='\n\x10ProtoTuple.proto\x12%eu.stratosphere.languagebinding.proto\"\x1a\n\tTupleSize\x12\r\n\x05value\x18\x01 \x02(\x0f\"\xa3\x03\n\nProtoTuple\x12\x12\n\natomicType\x18\x02 \x02(\x08\x12L\n\x06values\x18\x01 \x03(\x0b\x32<.eu.stratosphere.languagebinding.proto.ProtoTuple.FieldValue\x1a\xc9\x01\n\nFieldValue\x12N\n\tfieldType\x18\x01 \x02(\x0e\x32;.eu.stratosphere.languagebinding.proto.ProtoTuple.FieldType\x12\x11\n\tstringVal\x18\x02 \x01(\t\x12\x10\n\x08int32Val\x18\x03 \x01(\x05\x12\x10\n\x08int64Val\x18\x04 \x01(\x03\x12\x11\n\tdoubleVal\x18\x05 \x01(\x01\x12\x10\n\x08\x66loatVal\x18\x06 \x01(\x02\x12\x0f\n\x07\x62oolVal\x18\x07 \x01(\x08\"g\n\tFieldType\x12\n\n\x06String\x10\x00\x12\x08\n\x04\x42yte\x10\x01\x12\t\n\x05Short\x10\x02\x12\x0b\n\x07Integer\x10\x03\x12\x08\n\x04Long\x10\x04\x12\t\n\x05\x46loat\x10\x05\x12\n\n\x06\x44ouble\x10\x06\x12\x0b\n\x07\x42oolean\x10\x07\x42\x0f\x42\rProtocolTuple')

_PROTOTUPLE_FIELDTYPE = _descriptor.EnumDescriptor(
    name='FieldType',
    full_name='eu.stratosphere.languagebinding.proto.ProtoTuple.FieldType',
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name='String', index=0, number=0,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='Byte', index=1, number=1,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='Short', index=2, number=2,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='Integer', index=3, number=3,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='Long', index=4, number=4,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='Float', index=5, number=5,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='Double', index=6, number=6,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='Boolean', index=7, number=7,
            options=None,
            type=None),
    ],
    containing_type=None,
    options=None,
    serialized_start=404,
    serialized_end=507,
)

_TUPLESIZE = _descriptor.Descriptor(
    name='TupleSize',
    full_name='eu.stratosphere.languagebinding.proto.TupleSize',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='value', full_name='eu.stratosphere.languagebinding.proto.TupleSize.value', index=0,
            number=1, type=15, cpp_type=1, label=2,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    serialized_start=59,
    serialized_end=85,
)

_PROTOTUPLE_FIELDVALUE = _descriptor.Descriptor(
    name='FieldValue',
    full_name='eu.stratosphere.languagebinding.proto.ProtoTuple.FieldValue',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='fieldType', full_name='eu.stratosphere.languagebinding.proto.ProtoTuple.FieldValue.fieldType',
            index=0,
            number=1, type=14, cpp_type=8, label=2,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='stringVal', full_name='eu.stratosphere.languagebinding.proto.ProtoTuple.FieldValue.stringVal',
            index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=unicode("", "utf-8"),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='int32Val', full_name='eu.stratosphere.languagebinding.proto.ProtoTuple.FieldValue.int32Val', index=2,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='int64Val', full_name='eu.stratosphere.languagebinding.proto.ProtoTuple.FieldValue.int64Val', index=3,
            number=4, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='doubleVal', full_name='eu.stratosphere.languagebinding.proto.ProtoTuple.FieldValue.doubleVal',
            index=4,
            number=5, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='floatVal', full_name='eu.stratosphere.languagebinding.proto.ProtoTuple.FieldValue.floatVal', index=5,
            number=6, type=2, cpp_type=6, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='boolVal', full_name='eu.stratosphere.languagebinding.proto.ProtoTuple.FieldValue.boolVal', index=6,
            number=7, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    serialized_start=201,
    serialized_end=402,
)

_PROTOTUPLE = _descriptor.Descriptor(
    name='ProtoTuple',
    full_name='eu.stratosphere.languagebinding.proto.ProtoTuple',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='atomicType', full_name='eu.stratosphere.languagebinding.proto.ProtoTuple.atomicType', index=0,
            number=2, type=8, cpp_type=7, label=2,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='values', full_name='eu.stratosphere.languagebinding.proto.ProtoTuple.values', index=1,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[_PROTOTUPLE_FIELDVALUE, ],
    enum_types=[
        _PROTOTUPLE_FIELDTYPE,
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    serialized_start=88,
    serialized_end=507,
)

_PROTOTUPLE_FIELDVALUE.fields_by_name['fieldType'].enum_type = _PROTOTUPLE_FIELDTYPE
_PROTOTUPLE_FIELDVALUE.containing_type = _PROTOTUPLE;
_PROTOTUPLE.fields_by_name['values'].message_type = _PROTOTUPLE_FIELDVALUE
_PROTOTUPLE_FIELDTYPE.containing_type = _PROTOTUPLE;
DESCRIPTOR.message_types_by_name['TupleSize'] = _TUPLESIZE
DESCRIPTOR.message_types_by_name['ProtoTuple'] = _PROTOTUPLE


class TupleSize(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _TUPLESIZE

    # @@protoc_insertion_point(class_scope:eu.stratosphere.languagebinding.proto.TupleSize)


class ProtoTuple(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType

    class FieldValue(_message.Message):
        __metaclass__ = _reflection.GeneratedProtocolMessageType
        DESCRIPTOR = _PROTOTUPLE_FIELDVALUE

        # @@protoc_insertion_point(class_scope:eu.stratosphere.languagebinding.proto.ProtoTuple.FieldValue)

    DESCRIPTOR = _PROTOTUPLE

    # @@protoc_insertion_point(class_scope:eu.stratosphere.languagebinding.proto.ProtoTuple)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'B\rProtocolTuple')
# @@protoc_insertion_point(module_scope)
