# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stratosphereRecord.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stratosphereRecord.proto',
  package='eu.stratosphere.language.binding.protos',
  serialized_pb='\n\x18stratosphereRecord.proto\x12\'eu.stratosphere.language.binding.protos\" \n\x0fProtoRecordSize\x12\r\n\x05value\x18\x01 \x02(\x07\"\xd4\x03\n\x17ProtoStratosphereRecord\x12[\n\x06values\x18\x01 \x03(\x0b\x32K.eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue\x1a\xdd\x01\n\nProtoValue\x12\x62\n\tvalueType\x18\x01 \x02(\x0e\x32O.eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValueType\x12\x11\n\tstringVal\x18\x02 \x01(\t\x12\x10\n\x08int32Val\x18\x03 \x01(\x05\x12\x10\n\x08int64Val\x18\x04 \x01(\x03\x12\x11\n\tdoubleVal\x18\x05 \x01(\x01\x12\x10\n\x08\x66loatVal\x18\x06 \x01(\x02\x12\x0f\n\x07\x62oolVal\x18\x07 \x01(\x08\"|\n\x0eProtoValueType\x12\x0f\n\x0bStringValue\x10\x00\x12\x12\n\x0eIntegerValue32\x10\x01\x12\x12\n\x0eIntegerValue64\x10\x02\x12\x0f\n\x0b\x44oubleValue\x10\x03\x12\x0e\n\nFloatValue\x10\x04\x12\x10\n\x0c\x42ooleanValue\x10\x05\x42 B\x1eStratosphereRecordProtoBuffers')



_PROTOSTRATOSPHERERECORD_PROTOVALUETYPE = _descriptor.EnumDescriptor(
  name='ProtoValueType',
  full_name='eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValueType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='StringValue', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IntegerValue32', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IntegerValue64', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DoubleValue', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FloatValue', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BooleanValue', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=448,
  serialized_end=572,
)


_PROTORECORDSIZE = _descriptor.Descriptor(
  name='ProtoRecordSize',
  full_name='eu.stratosphere.language.binding.protos.ProtoRecordSize',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='eu.stratosphere.language.binding.protos.ProtoRecordSize.value', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=69,
  serialized_end=101,
)


_PROTOSTRATOSPHERERECORD_PROTOVALUE = _descriptor.Descriptor(
  name='ProtoValue',
  full_name='eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='valueType', full_name='eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue.valueType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stringVal', full_name='eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue.stringVal', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='int32Val', full_name='eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue.int32Val', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='int64Val', full_name='eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue.int64Val', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='doubleVal', full_name='eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue.doubleVal', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='floatVal', full_name='eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue.floatVal', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='boolVal', full_name='eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue.boolVal', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=225,
  serialized_end=446,
)

_PROTOSTRATOSPHERERECORD = _descriptor.Descriptor(
  name='ProtoStratosphereRecord',
  full_name='eu.stratosphere.language.binding.protos.ProtoStratosphereRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.values', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PROTOSTRATOSPHERERECORD_PROTOVALUE, ],
  enum_types=[
    _PROTOSTRATOSPHERERECORD_PROTOVALUETYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=104,
  serialized_end=572,
)

_PROTOSTRATOSPHERERECORD_PROTOVALUE.fields_by_name['valueType'].enum_type = _PROTOSTRATOSPHERERECORD_PROTOVALUETYPE
_PROTOSTRATOSPHERERECORD_PROTOVALUE.containing_type = _PROTOSTRATOSPHERERECORD;
_PROTOSTRATOSPHERERECORD.fields_by_name['values'].message_type = _PROTOSTRATOSPHERERECORD_PROTOVALUE
_PROTOSTRATOSPHERERECORD_PROTOVALUETYPE.containing_type = _PROTOSTRATOSPHERERECORD;
DESCRIPTOR.message_types_by_name['ProtoRecordSize'] = _PROTORECORDSIZE
DESCRIPTOR.message_types_by_name['ProtoStratosphereRecord'] = _PROTOSTRATOSPHERERECORD

class ProtoRecordSize(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROTORECORDSIZE

  # @@protoc_insertion_point(class_scope:eu.stratosphere.language.binding.protos.ProtoRecordSize)

class ProtoStratosphereRecord(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class ProtoValue(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PROTOSTRATOSPHERERECORD_PROTOVALUE

    # @@protoc_insertion_point(class_scope:eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue)
  DESCRIPTOR = _PROTOSTRATOSPHERERECORD

  # @@protoc_insertion_point(class_scope:eu.stratosphere.language.binding.protos.ProtoStratosphereRecord)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'B\036StratosphereRecordProtoBuffers')
# @@protoc_insertion_point(module_scope)
