// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stratosphereRecord.proto

package eu.stratosphere.language.binding.protos;

public final class StratosphereRecordProtoBuffers {
  private StratosphereRecordProtoBuffers() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ProtoRecordSizeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required fixed32 value = 1;
    /**
     * <code>required fixed32 value = 1;</code>
     */
    boolean hasValue();
    /**
     * <code>required fixed32 value = 1;</code>
     */
    int getValue();
  }
  /**
   * Protobuf type {@code eu.stratosphere.language.binding.protos.ProtoRecordSize}
   *
   * <pre>
   *As test for a fixed size length sending
   * </pre>
   */
  public static final class ProtoRecordSize extends
      com.google.protobuf.GeneratedMessage
      implements ProtoRecordSizeOrBuilder {
    // Use ProtoRecordSize.newBuilder() to construct.
    private ProtoRecordSize(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ProtoRecordSize(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ProtoRecordSize defaultInstance;
    public static ProtoRecordSize getDefaultInstance() {
      return defaultInstance;
    }

    public ProtoRecordSize getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ProtoRecordSize(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              value_ = input.readFixed32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.internal_static_eu_stratosphere_language_binding_protos_ProtoRecordSize_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.internal_static_eu_stratosphere_language_binding_protos_ProtoRecordSize_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoRecordSize.class, eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoRecordSize.Builder.class);
    }

    public static com.google.protobuf.Parser<ProtoRecordSize> PARSER =
        new com.google.protobuf.AbstractParser<ProtoRecordSize>() {
      public ProtoRecordSize parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoRecordSize(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoRecordSize> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required fixed32 value = 1;
    public static final int VALUE_FIELD_NUMBER = 1;
    private int value_;
    /**
     * <code>required fixed32 value = 1;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required fixed32 value = 1;</code>
     */
    public int getValue() {
      return value_;
    }

    private void initFields() {
      value_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFixed32(1, value_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(1, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoRecordSize parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoRecordSize parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoRecordSize parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoRecordSize parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoRecordSize parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoRecordSize parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoRecordSize parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoRecordSize parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoRecordSize parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoRecordSize parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoRecordSize prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code eu.stratosphere.language.binding.protos.ProtoRecordSize}
     *
     * <pre>
     *As test for a fixed size length sending
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoRecordSizeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.internal_static_eu_stratosphere_language_binding_protos_ProtoRecordSize_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.internal_static_eu_stratosphere_language_binding_protos_ProtoRecordSize_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoRecordSize.class, eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoRecordSize.Builder.class);
      }

      // Construct using eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoRecordSize.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        value_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.internal_static_eu_stratosphere_language_binding_protos_ProtoRecordSize_descriptor;
      }

      public eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoRecordSize getDefaultInstanceForType() {
        return eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoRecordSize.getDefaultInstance();
      }

      public eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoRecordSize build() {
        eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoRecordSize result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoRecordSize buildPartial() {
        eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoRecordSize result = new eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoRecordSize(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoRecordSize) {
          return mergeFrom((eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoRecordSize)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoRecordSize other) {
        if (other == eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoRecordSize.getDefaultInstance()) return this;
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoRecordSize parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoRecordSize) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required fixed32 value = 1;
      private int value_ ;
      /**
       * <code>required fixed32 value = 1;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required fixed32 value = 1;</code>
       */
      public int getValue() {
        return value_;
      }
      /**
       * <code>required fixed32 value = 1;</code>
       */
      public Builder setValue(int value) {
        bitField0_ |= 0x00000001;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed32 value = 1;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:eu.stratosphere.language.binding.protos.ProtoRecordSize)
    }

    static {
      defaultInstance = new ProtoRecordSize(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:eu.stratosphere.language.binding.protos.ProtoRecordSize)
  }

  public interface ProtoStratosphereRecordOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue values = 1;
    /**
     * <code>repeated .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue values = 1;</code>
     *
     * <pre>
     * Due to language-guide [packed = true] should be more efficient,
     * but it can only be applied to primitive fields
     * </pre>
     */
    java.util.List<eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue> 
        getValuesList();
    /**
     * <code>repeated .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue values = 1;</code>
     *
     * <pre>
     * Due to language-guide [packed = true] should be more efficient,
     * but it can only be applied to primitive fields
     * </pre>
     */
    eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue getValues(int index);
    /**
     * <code>repeated .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue values = 1;</code>
     *
     * <pre>
     * Due to language-guide [packed = true] should be more efficient,
     * but it can only be applied to primitive fields
     * </pre>
     */
    int getValuesCount();
    /**
     * <code>repeated .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue values = 1;</code>
     *
     * <pre>
     * Due to language-guide [packed = true] should be more efficient,
     * but it can only be applied to primitive fields
     * </pre>
     */
    java.util.List<? extends eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValueOrBuilder> 
        getValuesOrBuilderList();
    /**
     * <code>repeated .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue values = 1;</code>
     *
     * <pre>
     * Due to language-guide [packed = true] should be more efficient,
     * but it can only be applied to primitive fields
     * </pre>
     */
    eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValueOrBuilder getValuesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code eu.stratosphere.language.binding.protos.ProtoStratosphereRecord}
   */
  public static final class ProtoStratosphereRecord extends
      com.google.protobuf.GeneratedMessage
      implements ProtoStratosphereRecordOrBuilder {
    // Use ProtoStratosphereRecord.newBuilder() to construct.
    private ProtoStratosphereRecord(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ProtoStratosphereRecord(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ProtoStratosphereRecord defaultInstance;
    public static ProtoStratosphereRecord getDefaultInstance() {
      return defaultInstance;
    }

    public ProtoStratosphereRecord getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ProtoStratosphereRecord(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                values_ = new java.util.ArrayList<eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue>();
                mutable_bitField0_ |= 0x00000001;
              }
              values_.add(input.readMessage(eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          values_ = java.util.Collections.unmodifiableList(values_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.internal_static_eu_stratosphere_language_binding_protos_ProtoStratosphereRecord_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.internal_static_eu_stratosphere_language_binding_protos_ProtoStratosphereRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.class, eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.Builder.class);
    }

    public static com.google.protobuf.Parser<ProtoStratosphereRecord> PARSER =
        new com.google.protobuf.AbstractParser<ProtoStratosphereRecord>() {
      public ProtoStratosphereRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoStratosphereRecord(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoStratosphereRecord> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValueType}
     */
    public enum ProtoValueType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>StringValue = 0;</code>
       */
      StringValue(0, 0),
      /**
       * <code>IntegerValue32 = 1;</code>
       */
      IntegerValue32(1, 1),
      /**
       * <code>IntegerValue64 = 2;</code>
       */
      IntegerValue64(2, 2),
      /**
       * <code>DoubleValue = 3;</code>
       */
      DoubleValue(3, 3),
      /**
       * <code>FloatValue = 4;</code>
       */
      FloatValue(4, 4),
      /**
       * <code>BooleanValue = 5;</code>
       */
      BooleanValue(5, 5),
      ;

      /**
       * <code>StringValue = 0;</code>
       */
      public static final int StringValue_VALUE = 0;
      /**
       * <code>IntegerValue32 = 1;</code>
       */
      public static final int IntegerValue32_VALUE = 1;
      /**
       * <code>IntegerValue64 = 2;</code>
       */
      public static final int IntegerValue64_VALUE = 2;
      /**
       * <code>DoubleValue = 3;</code>
       */
      public static final int DoubleValue_VALUE = 3;
      /**
       * <code>FloatValue = 4;</code>
       */
      public static final int FloatValue_VALUE = 4;
      /**
       * <code>BooleanValue = 5;</code>
       */
      public static final int BooleanValue_VALUE = 5;


      public final int getNumber() { return value; }

      public static ProtoValueType valueOf(int value) {
        switch (value) {
          case 0: return StringValue;
          case 1: return IntegerValue32;
          case 2: return IntegerValue64;
          case 3: return DoubleValue;
          case 4: return FloatValue;
          case 5: return BooleanValue;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ProtoValueType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ProtoValueType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ProtoValueType>() {
              public ProtoValueType findValueByNumber(int number) {
                return ProtoValueType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.getDescriptor().getEnumTypes().get(0);
      }

      private static final ProtoValueType[] VALUES = values();

      public static ProtoValueType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ProtoValueType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValueType)
    }

    public interface ProtoValueOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValueType valueType = 1;
      /**
       * <code>required .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValueType valueType = 1;</code>
       */
      boolean hasValueType();
      /**
       * <code>required .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValueType valueType = 1;</code>
       */
      eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValueType getValueType();

      // optional string stringVal = 2;
      /**
       * <code>optional string stringVal = 2;</code>
       */
      boolean hasStringVal();
      /**
       * <code>optional string stringVal = 2;</code>
       */
      java.lang.String getStringVal();
      /**
       * <code>optional string stringVal = 2;</code>
       */
      com.google.protobuf.ByteString
          getStringValBytes();

      // optional int32 int32Val = 3;
      /**
       * <code>optional int32 int32Val = 3;</code>
       *
       * <pre>
       * Automatically using variable-length encoding,
       * but int32 is equivalent to int, int64 to long...
       * TODO look if we really need this differentiation
       * </pre>
       */
      boolean hasInt32Val();
      /**
       * <code>optional int32 int32Val = 3;</code>
       *
       * <pre>
       * Automatically using variable-length encoding,
       * but int32 is equivalent to int, int64 to long...
       * TODO look if we really need this differentiation
       * </pre>
       */
      int getInt32Val();

      // optional int64 int64Val = 4;
      /**
       * <code>optional int64 int64Val = 4;</code>
       */
      boolean hasInt64Val();
      /**
       * <code>optional int64 int64Val = 4;</code>
       */
      long getInt64Val();

      // optional double doubleVal = 5;
      /**
       * <code>optional double doubleVal = 5;</code>
       */
      boolean hasDoubleVal();
      /**
       * <code>optional double doubleVal = 5;</code>
       */
      double getDoubleVal();

      // optional float floatVal = 6;
      /**
       * <code>optional float floatVal = 6;</code>
       */
      boolean hasFloatVal();
      /**
       * <code>optional float floatVal = 6;</code>
       */
      float getFloatVal();

      // optional bool boolVal = 7;
      /**
       * <code>optional bool boolVal = 7;</code>
       */
      boolean hasBoolVal();
      /**
       * <code>optional bool boolVal = 7;</code>
       */
      boolean getBoolVal();
    }
    /**
     * Protobuf type {@code eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue}
     */
    public static final class ProtoValue extends
        com.google.protobuf.GeneratedMessage
        implements ProtoValueOrBuilder {
      // Use ProtoValue.newBuilder() to construct.
      private ProtoValue(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private ProtoValue(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final ProtoValue defaultInstance;
      public static ProtoValue getDefaultInstance() {
        return defaultInstance;
      }

      public ProtoValue getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private ProtoValue(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();
                eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValueType value = eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValueType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(1, rawValue);
                } else {
                  bitField0_ |= 0x00000001;
                  valueType_ = value;
                }
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                stringVal_ = input.readBytes();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                int32Val_ = input.readInt32();
                break;
              }
              case 32: {
                bitField0_ |= 0x00000008;
                int64Val_ = input.readInt64();
                break;
              }
              case 41: {
                bitField0_ |= 0x00000010;
                doubleVal_ = input.readDouble();
                break;
              }
              case 53: {
                bitField0_ |= 0x00000020;
                floatVal_ = input.readFloat();
                break;
              }
              case 56: {
                bitField0_ |= 0x00000040;
                boolVal_ = input.readBool();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.internal_static_eu_stratosphere_language_binding_protos_ProtoStratosphereRecord_ProtoValue_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.internal_static_eu_stratosphere_language_binding_protos_ProtoStratosphereRecord_ProtoValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue.class, eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue.Builder.class);
      }

      public static com.google.protobuf.Parser<ProtoValue> PARSER =
          new com.google.protobuf.AbstractParser<ProtoValue>() {
        public ProtoValue parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new ProtoValue(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<ProtoValue> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValueType valueType = 1;
      public static final int VALUETYPE_FIELD_NUMBER = 1;
      private eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValueType valueType_;
      /**
       * <code>required .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValueType valueType = 1;</code>
       */
      public boolean hasValueType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValueType valueType = 1;</code>
       */
      public eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValueType getValueType() {
        return valueType_;
      }

      // optional string stringVal = 2;
      public static final int STRINGVAL_FIELD_NUMBER = 2;
      private java.lang.Object stringVal_;
      /**
       * <code>optional string stringVal = 2;</code>
       */
      public boolean hasStringVal() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string stringVal = 2;</code>
       */
      public java.lang.String getStringVal() {
        java.lang.Object ref = stringVal_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            stringVal_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string stringVal = 2;</code>
       */
      public com.google.protobuf.ByteString
          getStringValBytes() {
        java.lang.Object ref = stringVal_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stringVal_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional int32 int32Val = 3;
      public static final int INT32VAL_FIELD_NUMBER = 3;
      private int int32Val_;
      /**
       * <code>optional int32 int32Val = 3;</code>
       *
       * <pre>
       * Automatically using variable-length encoding,
       * but int32 is equivalent to int, int64 to long...
       * TODO look if we really need this differentiation
       * </pre>
       */
      public boolean hasInt32Val() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 int32Val = 3;</code>
       *
       * <pre>
       * Automatically using variable-length encoding,
       * but int32 is equivalent to int, int64 to long...
       * TODO look if we really need this differentiation
       * </pre>
       */
      public int getInt32Val() {
        return int32Val_;
      }

      // optional int64 int64Val = 4;
      public static final int INT64VAL_FIELD_NUMBER = 4;
      private long int64Val_;
      /**
       * <code>optional int64 int64Val = 4;</code>
       */
      public boolean hasInt64Val() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 int64Val = 4;</code>
       */
      public long getInt64Val() {
        return int64Val_;
      }

      // optional double doubleVal = 5;
      public static final int DOUBLEVAL_FIELD_NUMBER = 5;
      private double doubleVal_;
      /**
       * <code>optional double doubleVal = 5;</code>
       */
      public boolean hasDoubleVal() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional double doubleVal = 5;</code>
       */
      public double getDoubleVal() {
        return doubleVal_;
      }

      // optional float floatVal = 6;
      public static final int FLOATVAL_FIELD_NUMBER = 6;
      private float floatVal_;
      /**
       * <code>optional float floatVal = 6;</code>
       */
      public boolean hasFloatVal() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional float floatVal = 6;</code>
       */
      public float getFloatVal() {
        return floatVal_;
      }

      // optional bool boolVal = 7;
      public static final int BOOLVAL_FIELD_NUMBER = 7;
      private boolean boolVal_;
      /**
       * <code>optional bool boolVal = 7;</code>
       */
      public boolean hasBoolVal() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bool boolVal = 7;</code>
       */
      public boolean getBoolVal() {
        return boolVal_;
      }

      private void initFields() {
        valueType_ = eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValueType.StringValue;
        stringVal_ = "";
        int32Val_ = 0;
        int64Val_ = 0L;
        doubleVal_ = 0D;
        floatVal_ = 0F;
        boolVal_ = false;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasValueType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeEnum(1, valueType_.getNumber());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getStringValBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt32(3, int32Val_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeInt64(4, int64Val_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeDouble(5, doubleVal_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeFloat(6, floatVal_);
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          output.writeBool(7, boolVal_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, valueType_.getNumber());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getStringValBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, int32Val_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(4, int64Val_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(5, doubleVal_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(6, floatVal_);
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(7, boolVal_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValueOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.internal_static_eu_stratosphere_language_binding_protos_ProtoStratosphereRecord_ProtoValue_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.internal_static_eu_stratosphere_language_binding_protos_ProtoStratosphereRecord_ProtoValue_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue.class, eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue.Builder.class);
        }

        // Construct using eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          valueType_ = eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValueType.StringValue;
          bitField0_ = (bitField0_ & ~0x00000001);
          stringVal_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          int32Val_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          int64Val_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000008);
          doubleVal_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000010);
          floatVal_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000020);
          boolVal_ = false;
          bitField0_ = (bitField0_ & ~0x00000040);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.internal_static_eu_stratosphere_language_binding_protos_ProtoStratosphereRecord_ProtoValue_descriptor;
        }

        public eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue getDefaultInstanceForType() {
          return eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue.getDefaultInstance();
        }

        public eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue build() {
          eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue buildPartial() {
          eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue result = new eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.valueType_ = valueType_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.stringVal_ = stringVal_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.int32Val_ = int32Val_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.int64Val_ = int64Val_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.doubleVal_ = doubleVal_;
          if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
            to_bitField0_ |= 0x00000020;
          }
          result.floatVal_ = floatVal_;
          if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
            to_bitField0_ |= 0x00000040;
          }
          result.boolVal_ = boolVal_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue) {
            return mergeFrom((eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue other) {
          if (other == eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue.getDefaultInstance()) return this;
          if (other.hasValueType()) {
            setValueType(other.getValueType());
          }
          if (other.hasStringVal()) {
            bitField0_ |= 0x00000002;
            stringVal_ = other.stringVal_;
            onChanged();
          }
          if (other.hasInt32Val()) {
            setInt32Val(other.getInt32Val());
          }
          if (other.hasInt64Val()) {
            setInt64Val(other.getInt64Val());
          }
          if (other.hasDoubleVal()) {
            setDoubleVal(other.getDoubleVal());
          }
          if (other.hasFloatVal()) {
            setFloatVal(other.getFloatVal());
          }
          if (other.hasBoolVal()) {
            setBoolVal(other.getBoolVal());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasValueType()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValueType valueType = 1;
        private eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValueType valueType_ = eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValueType.StringValue;
        /**
         * <code>required .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValueType valueType = 1;</code>
         */
        public boolean hasValueType() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValueType valueType = 1;</code>
         */
        public eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValueType getValueType() {
          return valueType_;
        }
        /**
         * <code>required .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValueType valueType = 1;</code>
         */
        public Builder setValueType(eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValueType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          valueType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValueType valueType = 1;</code>
         */
        public Builder clearValueType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          valueType_ = eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValueType.StringValue;
          onChanged();
          return this;
        }

        // optional string stringVal = 2;
        private java.lang.Object stringVal_ = "";
        /**
         * <code>optional string stringVal = 2;</code>
         */
        public boolean hasStringVal() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string stringVal = 2;</code>
         */
        public java.lang.String getStringVal() {
          java.lang.Object ref = stringVal_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            stringVal_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string stringVal = 2;</code>
         */
        public com.google.protobuf.ByteString
            getStringValBytes() {
          java.lang.Object ref = stringVal_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            stringVal_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string stringVal = 2;</code>
         */
        public Builder setStringVal(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          stringVal_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string stringVal = 2;</code>
         */
        public Builder clearStringVal() {
          bitField0_ = (bitField0_ & ~0x00000002);
          stringVal_ = getDefaultInstance().getStringVal();
          onChanged();
          return this;
        }
        /**
         * <code>optional string stringVal = 2;</code>
         */
        public Builder setStringValBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          stringVal_ = value;
          onChanged();
          return this;
        }

        // optional int32 int32Val = 3;
        private int int32Val_ ;
        /**
         * <code>optional int32 int32Val = 3;</code>
         *
         * <pre>
         * Automatically using variable-length encoding,
         * but int32 is equivalent to int, int64 to long...
         * TODO look if we really need this differentiation
         * </pre>
         */
        public boolean hasInt32Val() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional int32 int32Val = 3;</code>
         *
         * <pre>
         * Automatically using variable-length encoding,
         * but int32 is equivalent to int, int64 to long...
         * TODO look if we really need this differentiation
         * </pre>
         */
        public int getInt32Val() {
          return int32Val_;
        }
        /**
         * <code>optional int32 int32Val = 3;</code>
         *
         * <pre>
         * Automatically using variable-length encoding,
         * but int32 is equivalent to int, int64 to long...
         * TODO look if we really need this differentiation
         * </pre>
         */
        public Builder setInt32Val(int value) {
          bitField0_ |= 0x00000004;
          int32Val_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 int32Val = 3;</code>
         *
         * <pre>
         * Automatically using variable-length encoding,
         * but int32 is equivalent to int, int64 to long...
         * TODO look if we really need this differentiation
         * </pre>
         */
        public Builder clearInt32Val() {
          bitField0_ = (bitField0_ & ~0x00000004);
          int32Val_ = 0;
          onChanged();
          return this;
        }

        // optional int64 int64Val = 4;
        private long int64Val_ ;
        /**
         * <code>optional int64 int64Val = 4;</code>
         */
        public boolean hasInt64Val() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional int64 int64Val = 4;</code>
         */
        public long getInt64Val() {
          return int64Val_;
        }
        /**
         * <code>optional int64 int64Val = 4;</code>
         */
        public Builder setInt64Val(long value) {
          bitField0_ |= 0x00000008;
          int64Val_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 int64Val = 4;</code>
         */
        public Builder clearInt64Val() {
          bitField0_ = (bitField0_ & ~0x00000008);
          int64Val_ = 0L;
          onChanged();
          return this;
        }

        // optional double doubleVal = 5;
        private double doubleVal_ ;
        /**
         * <code>optional double doubleVal = 5;</code>
         */
        public boolean hasDoubleVal() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>optional double doubleVal = 5;</code>
         */
        public double getDoubleVal() {
          return doubleVal_;
        }
        /**
         * <code>optional double doubleVal = 5;</code>
         */
        public Builder setDoubleVal(double value) {
          bitField0_ |= 0x00000010;
          doubleVal_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional double doubleVal = 5;</code>
         */
        public Builder clearDoubleVal() {
          bitField0_ = (bitField0_ & ~0x00000010);
          doubleVal_ = 0D;
          onChanged();
          return this;
        }

        // optional float floatVal = 6;
        private float floatVal_ ;
        /**
         * <code>optional float floatVal = 6;</code>
         */
        public boolean hasFloatVal() {
          return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>optional float floatVal = 6;</code>
         */
        public float getFloatVal() {
          return floatVal_;
        }
        /**
         * <code>optional float floatVal = 6;</code>
         */
        public Builder setFloatVal(float value) {
          bitField0_ |= 0x00000020;
          floatVal_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional float floatVal = 6;</code>
         */
        public Builder clearFloatVal() {
          bitField0_ = (bitField0_ & ~0x00000020);
          floatVal_ = 0F;
          onChanged();
          return this;
        }

        // optional bool boolVal = 7;
        private boolean boolVal_ ;
        /**
         * <code>optional bool boolVal = 7;</code>
         */
        public boolean hasBoolVal() {
          return ((bitField0_ & 0x00000040) == 0x00000040);
        }
        /**
         * <code>optional bool boolVal = 7;</code>
         */
        public boolean getBoolVal() {
          return boolVal_;
        }
        /**
         * <code>optional bool boolVal = 7;</code>
         */
        public Builder setBoolVal(boolean value) {
          bitField0_ |= 0x00000040;
          boolVal_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bool boolVal = 7;</code>
         */
        public Builder clearBoolVal() {
          bitField0_ = (bitField0_ & ~0x00000040);
          boolVal_ = false;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue)
      }

      static {
        defaultInstance = new ProtoValue(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue)
    }

    // repeated .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue values = 1;
    public static final int VALUES_FIELD_NUMBER = 1;
    private java.util.List<eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue> values_;
    /**
     * <code>repeated .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue values = 1;</code>
     *
     * <pre>
     * Due to language-guide [packed = true] should be more efficient,
     * but it can only be applied to primitive fields
     * </pre>
     */
    public java.util.List<eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue> getValuesList() {
      return values_;
    }
    /**
     * <code>repeated .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue values = 1;</code>
     *
     * <pre>
     * Due to language-guide [packed = true] should be more efficient,
     * but it can only be applied to primitive fields
     * </pre>
     */
    public java.util.List<? extends eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValueOrBuilder> 
        getValuesOrBuilderList() {
      return values_;
    }
    /**
     * <code>repeated .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue values = 1;</code>
     *
     * <pre>
     * Due to language-guide [packed = true] should be more efficient,
     * but it can only be applied to primitive fields
     * </pre>
     */
    public int getValuesCount() {
      return values_.size();
    }
    /**
     * <code>repeated .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue values = 1;</code>
     *
     * <pre>
     * Due to language-guide [packed = true] should be more efficient,
     * but it can only be applied to primitive fields
     * </pre>
     */
    public eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue getValues(int index) {
      return values_.get(index);
    }
    /**
     * <code>repeated .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue values = 1;</code>
     *
     * <pre>
     * Due to language-guide [packed = true] should be more efficient,
     * but it can only be applied to primitive fields
     * </pre>
     */
    public eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValueOrBuilder getValuesOrBuilder(
        int index) {
      return values_.get(index);
    }

    private void initFields() {
      values_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getValuesCount(); i++) {
        if (!getValues(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < values_.size(); i++) {
        output.writeMessage(1, values_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < values_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, values_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code eu.stratosphere.language.binding.protos.ProtoStratosphereRecord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.internal_static_eu_stratosphere_language_binding_protos_ProtoStratosphereRecord_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.internal_static_eu_stratosphere_language_binding_protos_ProtoStratosphereRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.class, eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.Builder.class);
      }

      // Construct using eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getValuesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (valuesBuilder_ == null) {
          values_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          valuesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.internal_static_eu_stratosphere_language_binding_protos_ProtoStratosphereRecord_descriptor;
      }

      public eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord getDefaultInstanceForType() {
        return eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.getDefaultInstance();
      }

      public eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord build() {
        eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord buildPartial() {
        eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord result = new eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord(this);
        int from_bitField0_ = bitField0_;
        if (valuesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            values_ = java.util.Collections.unmodifiableList(values_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.values_ = values_;
        } else {
          result.values_ = valuesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord) {
          return mergeFrom((eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord other) {
        if (other == eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.getDefaultInstance()) return this;
        if (valuesBuilder_ == null) {
          if (!other.values_.isEmpty()) {
            if (values_.isEmpty()) {
              values_ = other.values_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureValuesIsMutable();
              values_.addAll(other.values_);
            }
            onChanged();
          }
        } else {
          if (!other.values_.isEmpty()) {
            if (valuesBuilder_.isEmpty()) {
              valuesBuilder_.dispose();
              valuesBuilder_ = null;
              values_ = other.values_;
              bitField0_ = (bitField0_ & ~0x00000001);
              valuesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getValuesFieldBuilder() : null;
            } else {
              valuesBuilder_.addAllMessages(other.values_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getValuesCount(); i++) {
          if (!getValues(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue values = 1;
      private java.util.List<eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue> values_ =
        java.util.Collections.emptyList();
      private void ensureValuesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          values_ = new java.util.ArrayList<eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue>(values_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue, eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue.Builder, eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValueOrBuilder> valuesBuilder_;

      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue values = 1;</code>
       *
       * <pre>
       * Due to language-guide [packed = true] should be more efficient,
       * but it can only be applied to primitive fields
       * </pre>
       */
      public java.util.List<eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue> getValuesList() {
        if (valuesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(values_);
        } else {
          return valuesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue values = 1;</code>
       *
       * <pre>
       * Due to language-guide [packed = true] should be more efficient,
       * but it can only be applied to primitive fields
       * </pre>
       */
      public int getValuesCount() {
        if (valuesBuilder_ == null) {
          return values_.size();
        } else {
          return valuesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue values = 1;</code>
       *
       * <pre>
       * Due to language-guide [packed = true] should be more efficient,
       * but it can only be applied to primitive fields
       * </pre>
       */
      public eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue getValues(int index) {
        if (valuesBuilder_ == null) {
          return values_.get(index);
        } else {
          return valuesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue values = 1;</code>
       *
       * <pre>
       * Due to language-guide [packed = true] should be more efficient,
       * but it can only be applied to primitive fields
       * </pre>
       */
      public Builder setValues(
          int index, eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue value) {
        if (valuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValuesIsMutable();
          values_.set(index, value);
          onChanged();
        } else {
          valuesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue values = 1;</code>
       *
       * <pre>
       * Due to language-guide [packed = true] should be more efficient,
       * but it can only be applied to primitive fields
       * </pre>
       */
      public Builder setValues(
          int index, eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue.Builder builderForValue) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          values_.set(index, builderForValue.build());
          onChanged();
        } else {
          valuesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue values = 1;</code>
       *
       * <pre>
       * Due to language-guide [packed = true] should be more efficient,
       * but it can only be applied to primitive fields
       * </pre>
       */
      public Builder addValues(eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue value) {
        if (valuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValuesIsMutable();
          values_.add(value);
          onChanged();
        } else {
          valuesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue values = 1;</code>
       *
       * <pre>
       * Due to language-guide [packed = true] should be more efficient,
       * but it can only be applied to primitive fields
       * </pre>
       */
      public Builder addValues(
          int index, eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue value) {
        if (valuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValuesIsMutable();
          values_.add(index, value);
          onChanged();
        } else {
          valuesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue values = 1;</code>
       *
       * <pre>
       * Due to language-guide [packed = true] should be more efficient,
       * but it can only be applied to primitive fields
       * </pre>
       */
      public Builder addValues(
          eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue.Builder builderForValue) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          values_.add(builderForValue.build());
          onChanged();
        } else {
          valuesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue values = 1;</code>
       *
       * <pre>
       * Due to language-guide [packed = true] should be more efficient,
       * but it can only be applied to primitive fields
       * </pre>
       */
      public Builder addValues(
          int index, eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue.Builder builderForValue) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          values_.add(index, builderForValue.build());
          onChanged();
        } else {
          valuesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue values = 1;</code>
       *
       * <pre>
       * Due to language-guide [packed = true] should be more efficient,
       * but it can only be applied to primitive fields
       * </pre>
       */
      public Builder addAllValues(
          java.lang.Iterable<? extends eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue> values) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          super.addAll(values, values_);
          onChanged();
        } else {
          valuesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue values = 1;</code>
       *
       * <pre>
       * Due to language-guide [packed = true] should be more efficient,
       * but it can only be applied to primitive fields
       * </pre>
       */
      public Builder clearValues() {
        if (valuesBuilder_ == null) {
          values_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          valuesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue values = 1;</code>
       *
       * <pre>
       * Due to language-guide [packed = true] should be more efficient,
       * but it can only be applied to primitive fields
       * </pre>
       */
      public Builder removeValues(int index) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          values_.remove(index);
          onChanged();
        } else {
          valuesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue values = 1;</code>
       *
       * <pre>
       * Due to language-guide [packed = true] should be more efficient,
       * but it can only be applied to primitive fields
       * </pre>
       */
      public eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue.Builder getValuesBuilder(
          int index) {
        return getValuesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue values = 1;</code>
       *
       * <pre>
       * Due to language-guide [packed = true] should be more efficient,
       * but it can only be applied to primitive fields
       * </pre>
       */
      public eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValueOrBuilder getValuesOrBuilder(
          int index) {
        if (valuesBuilder_ == null) {
          return values_.get(index);  } else {
          return valuesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue values = 1;</code>
       *
       * <pre>
       * Due to language-guide [packed = true] should be more efficient,
       * but it can only be applied to primitive fields
       * </pre>
       */
      public java.util.List<? extends eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValueOrBuilder> 
           getValuesOrBuilderList() {
        if (valuesBuilder_ != null) {
          return valuesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(values_);
        }
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue values = 1;</code>
       *
       * <pre>
       * Due to language-guide [packed = true] should be more efficient,
       * but it can only be applied to primitive fields
       * </pre>
       */
      public eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue.Builder addValuesBuilder() {
        return getValuesFieldBuilder().addBuilder(
            eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue.getDefaultInstance());
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue values = 1;</code>
       *
       * <pre>
       * Due to language-guide [packed = true] should be more efficient,
       * but it can only be applied to primitive fields
       * </pre>
       */
      public eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue.Builder addValuesBuilder(
          int index) {
        return getValuesFieldBuilder().addBuilder(
            index, eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue.getDefaultInstance());
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.ProtoStratosphereRecord.ProtoValue values = 1;</code>
       *
       * <pre>
       * Due to language-guide [packed = true] should be more efficient,
       * but it can only be applied to primitive fields
       * </pre>
       */
      public java.util.List<eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue.Builder> 
           getValuesBuilderList() {
        return getValuesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue, eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue.Builder, eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValueOrBuilder> 
          getValuesFieldBuilder() {
        if (valuesBuilder_ == null) {
          valuesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue, eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValue.Builder, eu.stratosphere.language.binding.protos.StratosphereRecordProtoBuffers.ProtoStratosphereRecord.ProtoValueOrBuilder>(
                  values_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          values_ = null;
        }
        return valuesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:eu.stratosphere.language.binding.protos.ProtoStratosphereRecord)
    }

    static {
      defaultInstance = new ProtoStratosphereRecord(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:eu.stratosphere.language.binding.protos.ProtoStratosphereRecord)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_stratosphere_language_binding_protos_ProtoRecordSize_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_stratosphere_language_binding_protos_ProtoRecordSize_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_stratosphere_language_binding_protos_ProtoStratosphereRecord_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_stratosphere_language_binding_protos_ProtoStratosphereRecord_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_stratosphere_language_binding_protos_ProtoStratosphereRecord_ProtoValue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_stratosphere_language_binding_protos_ProtoStratosphereRecord_ProtoValue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030stratosphereRecord.proto\022\'eu.stratosph" +
      "ere.language.binding.protos\" \n\017ProtoReco" +
      "rdSize\022\r\n\005value\030\001 \002(\007\"\324\003\n\027ProtoStratosph" +
      "ereRecord\022[\n\006values\030\001 \003(\0132K.eu.stratosph" +
      "ere.language.binding.protos.ProtoStratos" +
      "phereRecord.ProtoValue\032\335\001\n\nProtoValue\022b\n" +
      "\tvalueType\030\001 \002(\0162O.eu.stratosphere.langu" +
      "age.binding.protos.ProtoStratosphereReco" +
      "rd.ProtoValueType\022\021\n\tstringVal\030\002 \001(\t\022\020\n\010" +
      "int32Val\030\003 \001(\005\022\020\n\010int64Val\030\004 \001(\003\022\021\n\tdoub",
      "leVal\030\005 \001(\001\022\020\n\010floatVal\030\006 \001(\002\022\017\n\007boolVal" +
      "\030\007 \001(\010\"|\n\016ProtoValueType\022\017\n\013StringValue\020" +
      "\000\022\022\n\016IntegerValue32\020\001\022\022\n\016IntegerValue64\020" +
      "\002\022\017\n\013DoubleValue\020\003\022\016\n\nFloatValue\020\004\022\020\n\014Bo" +
      "oleanValue\020\005B B\036StratosphereRecordProtoB" +
      "uffers"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_eu_stratosphere_language_binding_protos_ProtoRecordSize_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_eu_stratosphere_language_binding_protos_ProtoRecordSize_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_eu_stratosphere_language_binding_protos_ProtoRecordSize_descriptor,
              new java.lang.String[] { "Value", });
          internal_static_eu_stratosphere_language_binding_protos_ProtoStratosphereRecord_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_eu_stratosphere_language_binding_protos_ProtoStratosphereRecord_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_eu_stratosphere_language_binding_protos_ProtoStratosphereRecord_descriptor,
              new java.lang.String[] { "Values", });
          internal_static_eu_stratosphere_language_binding_protos_ProtoStratosphereRecord_ProtoValue_descriptor =
            internal_static_eu_stratosphere_language_binding_protos_ProtoStratosphereRecord_descriptor.getNestedTypes().get(0);
          internal_static_eu_stratosphere_language_binding_protos_ProtoStratosphereRecord_ProtoValue_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_eu_stratosphere_language_binding_protos_ProtoStratosphereRecord_ProtoValue_descriptor,
              new java.lang.String[] { "ValueType", "StringVal", "Int32Val", "Int64Val", "DoubleVal", "FloatVal", "BoolVal", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
